### PR TITLE
fix: route snapshot missing entries fix

### PR DESCRIPTION
**Pull request by acelebanski**
## Description

The route table snapshot was missing entries when ECMP routes (differed only by next-hop) were present. This was because dict key generation was based only on VR name, destination CIDR and interface (if applicable). This PR adds next-hop IP address or name to dict key, so the keys are unique every time.

## Motivation and Context

#56 

## How Has This Been Tested?

It has been tested with example python scripts.

## Types of changes

- Bug fix (non-breaking change which fixes an issue)

## Checklist

- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes if appropriate.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by alperenkose — COMMENTED** [review]
Lets check if we have a similar issue with get fib routes, if different next hop is possible for same destination/interface. We can merge this afterwards.

**Comment by acelebanski** [comment]
> Lets check if we have a similar issue with get fib routes, if different next hop is possible for same destination/interface. We can merge this afterwards.

We had identical issue with FIB entries when ECMP was used, nice catch @alperenkose! Updated the PR accordingly.

**Review by adambaumeister — APPROVED** [review]
Makes sense, LGTM

**Review by alperenkose — APPROVED** [review]

**Pull request merged**
